### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by paulcgt** [OnBeep/splunk_graphite#10]
Hi there, I've been using your Splunk app for some time - thank you for publishing it! 

Do you have a plan to support Python 3 in future?

Thanks,
Paul.

**Comment by ampledata** [comment]
Hi Paul, I'm glad you find this project useful. We do not plan to update this code to support Python 3 ourselves. Patches are welcome and you are welcome to take and modify to suite your needs. I apologize for any inconvenience this may cause.

**Comment by paulcgt** [comment]
Hi Greg, thanks for getting back to me. I'll test, make changes if necessary, and create a PR. If you're happy with it, it'll be great if you could merge it in.
